version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: java21_postgres
    environment:
      POSTGRES_DB: seubanco
      POSTGRES_USER: seuusuario
      POSTGRES_PASSWORD: suasenha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
